### ISSUE TITLE
Fix common origin policy bug on OpenLayers demo

### ISSUE THREAD

**Issue by juliatruitt** [cs210/orbit-code#20]
When time slider is dragged, getting error: "Failed to load http://droughtmonitor.unl.edu/data/kmz/usdm_20180227.kmz: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access."

**Comment by guifereis** [comment]
Fixed both CORS & XML bugs. The problem was that OL expects .kml, not .kmz like google.
